extends SceneTree
const TestKit = preload("res://scripts/tests/test_kit.gd")

func _init() -> void:
	var t := TestKit.new()

	t.check(t.approx(Tuning.DT, 1.0 / 60.0), "Tuning.DT approx 1.0 / 60.0")
	t.check(Tuning.SPIN_CAP.size() == 4, "Tuning.SPIN_CAP.size() == 4")
	t.check(Tuning.SPIN_CAP[3] == 250.0, "Tuning.SPIN_CAP[3] == 250.0")
	t.check(Tuning.RANK_MULT == [1.0, 1.25, 1.6, 2.2], "Tuning.RANK_MULT == [1.0, 1.25, 1.6, 2.2]")
	t.check(Tuning.RANK_XP[2] == 120, "Tuning.RANK_XP[2] == 120")
	t.check(Tuning.WEAPON_NAMES.size() == Tuning.WEAPON_COUNT, "Tuning.WEAPON_NAMES.size() == Tuning.WEAPON_COUNT")
	t.check(Tuning.WEAPON_REACH.size() == Tuning.WEAPON_COUNT, "Tuning.WEAPON_REACH.size() == Tuning.WEAPON_COUNT")
	t.check(Tuning.WEAPON_DMG.size() == Tuning.WEAPON_COUNT, "Tuning.WEAPON_DMG.size() == Tuning.WEAPON_COUNT")
	t.check(Tuning.WEAPON_COOLDOWN.size() == Tuning.WEAPON_COUNT, "Tuning.WEAPON_COOLDOWN.size() == Tuning.WEAPON_COUNT")
	t.check(Tuning.WEAPON_KB.size() == Tuning.WEAPON_COUNT, "Tuning.WEAPON_KB.size() == Tuning.WEAPON_COUNT")
	t.check(Tuning.WEAPON_HIT_R.size() == Tuning.WEAPON_COUNT, "Tuning.WEAPON_HIT_R.size() == Tuning.WEAPON_COUNT")
	t.check(Tuning.WEAPON_REACH[2] == 2.0, "Tuning.WEAPON_REACH[2] == 2.0 (spear outranges)")
	t.check(Tuning.WEAPON_DMG[3] > Tuning.WEAPON_DMG[1], "Tuning.WEAPON_DMG[3] > Tuning.WEAPON_DMG[1] (axe > sword)")
	t.check(Tuning.FACTION_COLORS.size() == 16, "Tuning.FACTION_COLORS.size() == 16")
	t.check(Tuning.HOME_DIR.size() == 4, "Tuning.HOME_DIR.size() == 4")
	t.check(Tuning.HOME_DIR[1] == Vector2(1, 0), "Tuning.HOME_DIR[1] == Vector2(1, 0)")
	t.check(t.approx(Tuning.SPIN_TO_RAD, 0.10471976), "Tuning.SPIN_TO_RAD approx 0.10471976")
	t.check(Tuning.ARENA_W == 1600.0, "Tuning.ARENA_W == 1600.0")
	t.check(Tuning.ARENA_H == 900.0, "Tuning.ARENA_H == 900.0")
	t.check(Tuning.T_MAX_BATTLE == 120.0, "Tuning.T_MAX_BATTLE == 120.0")
	t.check(Tuning.K_ADVANCE == 20.0, "Tuning.K_ADVANCE == 20.0")
	t.check(Tuning.HAZARD_DPS.size() == 11, "Tuning.HAZARD_DPS.size() == 11")
	t.check(Tuning.HAZARD_DPS[8] == 8.0, "Tuning.HAZARD_DPS[8] == 8.0")
	t.check(Tuning.HAZARD_DPS[9] == 15.0, "Tuning.HAZARD_DPS[9] == 15.0")
	t.check(Tuning.HAZARD_DPS[0] == 0.0, "Tuning.HAZARD_DPS[0] == 0.0")
	t.check(Tuning.HAZARD_DPS[10] == 0.0, "Tuning.HAZARD_DPS[10] == 0.0")
	t.check(Tuning.DRAG_KEEP_PER_S.size() == 11, "Tuning.DRAG_KEEP_PER_S.size() == 11")
	t.check(t.approx(Tuning.DRAG_KEEP_PER_S[0], 0.12), "Tuning.DRAG_KEEP_PER_S[0] == 0.12")  # M8 pace
	t.check(t.approx(Tuning.DRAG_KEEP_PER_S[4], 0.01), "Tuning.DRAG_KEEP_PER_S[4] == 0.01")  # M8 pace
	t.check(Tuning.SPIN_RATE.size() == 11, "Tuning.SPIN_RATE.size() == 11")
	t.check(Tuning.SPIN_RATE[0] == 3.0, "Tuning.SPIN_RATE[0] == 3.0")
	t.check(Tuning.SPIN_RATE[1] == -15.0, "Tuning.SPIN_RATE[1] == -15.0")
	t.check(Tuning.SPIN_RATE[10] == 12.0, "Tuning.SPIN_RATE[10] == 12.0")
	t.check(Tuning.WEAPON_CRIT_CHANCE.size() == Tuning.WEAPON_COUNT, "Tuning.WEAPON_CRIT_CHANCE.size() == Tuning.WEAPON_COUNT")
	t.check(Tuning.WEAPON_CRIT_CHANCE[0] == 0.15, "Tuning.WEAPON_CRIT_CHANCE[0] == 0.15")
	t.check(Tuning.WEAPON_CRIT_CHANCE[3] == 0.0, "Tuning.WEAPON_CRIT_CHANCE[3] == 0.0")
	t.check(Tuning.BODY_DMG * 1.0 < Tuning.WEAPON_DMG[0] * Tuning.WEAPON_DMG_MULT, "Tuning.BODY_DMG * 1.0 < Tuning.WEAPON_DMG[0] * Tuning.WEAPON_DMG_MULT")
	t.check(Tuning.CRIT_MULT == 2.0, "Tuning.CRIT_MULT == 2.0")
	t.check(Tuning.FRICTION_WATER == 0.70, "Tuning.FRICTION_WATER == 0.70")
	t.check(Tuning.FRICTION_ICE == 0.99, "Tuning.FRICTION_ICE == 0.99")
	t.check(Tuning.TERRAIN_CELL == 40.0, "Tuning.TERRAIN_CELL == 40.0")
	t.check(Tuning.OBSTACLE_RADIUS_FRAC == 0.4, "Tuning.OBSTACLE_RADIUS_FRAC == 0.4")
	t.check(Tuning.CAPTAIN_AURA_MULT == 6.0, "Tuning.CAPTAIN_AURA_MULT == 6.0")
	t.check(Tuning.KB_SPIN_RESIST_MIN == 0.5, "Tuning.KB_SPIN_RESIST_MIN == 0.5")
	t.check(Tuning.WORLD_COLS == 96, "Tuning.WORLD_COLS == 96")
	t.check(Tuning.TILE == 32.0, "Tuning.TILE == 32.0")
	t.check(Tuning.TILE_COST.size() == 8, "Tuning.TILE_COST.size() == 8")
	t.check(Tuning.TILE_COST[3] == 0.0, "Tuning.TILE_COST[3] == 0.0")
	t.check(Tuning.TIER_NAMES.size() == 4, "Tuning.TIER_NAMES.size() == 4")
	t.check(Tuning.GOAL_WEIGHTS.size() == 5, "Tuning.GOAL_WEIGHTS.size() == 5")
	t.check(Tuning.STACK_CAP == 300, "Tuning.STACK_CAP == 300")
	t.check(Tuning.MAX_BATTLE_MARBLES == 3000, "Tuning.MAX_BATTLE_MARBLES == 3000")

	t.check(Tuning.PLINKO_SLOTS == 9, "Tuning.PLINKO_SLOTS == 9")
	t.check(Tuning.RECRUIT_N.size() == 4, "Tuning.RECRUIT_N.size() == 4")
	t.check(Tuning.BORDER_RANGE == 10, "Tuning.BORDER_RANGE == 10")

	t.check(Tuning.TRAIT_THRESHOLD == 3, "Tuning.TRAIT_THRESHOLD == 3")
	t.check(Tuning.LEGEND_RANK == 3, "Tuning.LEGEND_RANK == 3")
	t.check(Tuning.KTRAIT_INIT == 0.5, "Tuning.KTRAIT_INIT == 0.5")
	t.check(Tuning.REL_ALLY_THRESHOLD == 0.5, "Tuning.REL_ALLY_THRESHOLD == 0.5")
	t.check(Tuning.MAX_FACTIONS_WORLD == 64, "Tuning.MAX_FACTIONS_WORLD == 64")
	t.check(Tuning.SPLIT_UNITS == 600, "Tuning.SPLIT_UNITS == 600")
	t.check(Tuning.PLINKO_BIAS_GREED == 200.0, "Tuning.PLINKO_BIAS_GREED == 200.0")

	t.check(Tuning.SAVE_VERSION == 2, "Tuning.SAVE_VERSION == 2")
	t.check(Tuning.SPEED_STEPS.size() == 3, "Tuning.SPEED_STEPS.size() == 3")

	t.check(Tuning.ALLY_MIN_VREL == 80.0, "Tuning.ALLY_MIN_VREL == 80.0")
	t.check(Tuning.BOOST_COOLDOWN == 1.5, "Tuning.BOOST_COOLDOWN == 1.5")

	t.check(Tuning.CRUISE_SPEED == 50.0, "Tuning.CRUISE_SPEED == 50.0")  # M8 pace
	t.check(Tuning.CHARGE_SPEED == 160.0, "Tuning.CHARGE_SPEED == 160.0")  # M8 pace
	t.check(Tuning.RETREAT_SPEED == 80.0, "Tuning.RETREAT_SPEED == 80.0")  # M8 pace
	t.check(Tuning.STRIKE_RANGE_MULT == 6.0, "Tuning.STRIKE_RANGE_MULT == 6.0")
	t.check(Tuning.RECOIL_TIME == 0.45, "Tuning.RECOIL_TIME == 0.45")
	t.check(Tuning.K_RECOIL == 25.0, "Tuning.K_RECOIL == 25.0")
	t.check(Tuning.OUTMATCH_RATIO == 1.25, "Tuning.OUTMATCH_RATIO == 1.25")
	t.check(Tuning.CROWD_PENALTY == 8.0, "Tuning.CROWD_PENALTY == 8.0")
	t.check(Tuning.FINISH_HP_FRAC == 0.35, "Tuning.FINISH_HP_FRAC == 0.35")
	t.check(Tuning.FINISH_BONUS == 4.0, "Tuning.FINISH_BONUS == 4.0")
	t.check(Tuning.STICKY_BONUS == 2.0, "Tuning.STICKY_BONUS == 2.0")
	t.check(Tuning.SPREAD_KEEP == 1.0, "Tuning.SPREAD_KEEP == 1.0")
	t.check(Tuning.CRUISE_SPEED < Tuning.RETREAT_SPEED and Tuning.RETREAT_SPEED < Tuning.CHARGE_SPEED and Tuning.CHARGE_SPEED <= Tuning.MAX_SPEED, "CRUISE_SPEED < RETREAT_SPEED and RETREAT_SPEED < CHARGE_SPEED and CHARGE_SPEED <= MAX_SPEED")

	t.check(Tuning.HERO_LIFESPAN == 900.0, "Tuning.HERO_LIFESPAN == 900.0")
	t.check(Tuning.KINGDOMS_MIN == 2, "Tuning.KINGDOMS_MIN == 2")
	t.check(Tuning.RECRUIT_COST == 2.0, "Tuning.RECRUIT_COST == 2.0")
	t.check(Tuning.FOUND_SCORE == 200.0, "Tuning.FOUND_SCORE == 200.0")
	t.check(Tuning.FACTION_COLORS.size() == 16, "Tuning.FACTION_COLORS.size() == 16")
	t.check(Tuning.FACTION_COLORS[8] == Color(0.95,0.4,0.6), "Tuning.FACTION_COLORS[8] == Color(0.95,0.4,0.6)")

	var rng_epithet := RandomNumberGenerator.new()
	rng_epithet.seed = 5
	var epithet1 := NameGen.hero_epithet(rng_epithet)
	t.check(NameGen.LEGEND_ADJECTIVES.has(epithet1), "NameGen.hero_epithet(rng seeded 5) returns a String in LEGEND_ADJECTIVES")
	var rng_epithet2 := RandomNumberGenerator.new()
	rng_epithet2.seed = 5
	var epithet2 := NameGen.hero_epithet(rng_epithet2)
	t.check(epithet1 == epithet2, "two rngs seeded 5 return the same value from NameGen.hero_epithet")

	t.finish()
	quit()
